// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/blackhorseya/irent/internal/pkg/infra/transports/restclient"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateIRepo serve caller to create an IRepo
func CreateIRepo(o *Options, client restclient.HTTPClient) (IRepo, error) {
	iRepo := NewImpl(o, client)
	return iRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
