// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/gocommon/pkg/contextx"
	car "github.com/blackhorseya/irent/internal/pkg/entity/car"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IRepo is an autogenerated mock type for the IRepo type
type IRepo struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *IRepo) List(ctx contextx.Contextx) ([]*car.Info, error) {
	ret := _m.Called(ctx)

	var r0 []*car.Info
	if rf, ok := ret.Get(0).(func(contextx.Contextx) []*car.Info); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*car.Info)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIRepo creates a new instance of IRepo. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIRepo(t testing.TB) *IRepo {
	mock := &IRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
