// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package runner

import (
	"github.com/blackhorseya/irent/internal/app/irent/biz/order"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func CreateRunner(o *Options, logger *zap.Logger, orderBiz order.IBiz) (Runner, error) {
	runner := NewImpl(o, logger, orderBiz)
	return runner, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
