app:
  name: irent
  endpoint: https://irentcar-app.azurefd.net/api
  appVersion: "5.8.1"

http:
  port: 8080
  mode: debug

runner:
  interval: 5s
  shift: 5m

premium:
  people:
    - "C121463993"

log:
  level: debug
  encoding: console
